/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateItineraryInput = {
  id?: string | null,
  isRoot: boolean,
  name: string,
  description?: string | null,
  start: TimeLocationInput,
  end: TimeLocationInput,
  code?: Code | null,
  parentID: string,
  _version?: number | null,
};

export type TimeLocationInput = {
  time: string,
  lat?: number | null,
  long?: number | null,
};

export enum Code {
  FIXED = "FIXED",
  FLEXIBLE = "FLEXIBLE",
  TRANSIT = "TRANSIT",
}


export type ModelItineraryConditionInput = {
  isRoot?: ModelBooleanInput | null,
  name?: ModelStringInput | null,
  description?: ModelStringInput | null,
  code?: ModelCodeInput | null,
  parentID?: ModelIDInput | null,
  and?: Array< ModelItineraryConditionInput | null > | null,
  or?: Array< ModelItineraryConditionInput | null > | null,
  not?: ModelItineraryConditionInput | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelCodeInput = {
  eq?: Code | null,
  ne?: Code | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type UpdateItineraryInput = {
  id: string,
  isRoot?: boolean | null,
  name?: string | null,
  description?: string | null,
  start?: TimeLocationInput | null,
  end?: TimeLocationInput | null,
  code?: Code | null,
  parentID?: string | null,
  _version?: number | null,
};

export type DeleteItineraryInput = {
  id?: string | null,
  _version?: number | null,
};

export type ModelItineraryFilterInput = {
  id?: ModelIDInput | null,
  isRoot?: ModelBooleanInput | null,
  name?: ModelStringInput | null,
  description?: ModelStringInput | null,
  code?: ModelCodeInput | null,
  parentID?: ModelIDInput | null,
  and?: Array< ModelItineraryFilterInput | null > | null,
  or?: Array< ModelItineraryFilterInput | null > | null,
  not?: ModelItineraryFilterInput | null,
};

export type CreateItineraryMutationVariables = {
  input: CreateItineraryInput,
  condition?: ModelItineraryConditionInput | null,
};

export type CreateItineraryMutation = {
  createItinerary:  {
    __typename: "Itinerary",
    id: string,
    isRoot: boolean,
    name: string,
    description: string | null,
    start:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    end:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    code: Code | null,
    parentID: string,
    parent:  {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null,
    children:  {
      __typename: "ModelItineraryConnection",
      items:  Array< {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
    owner: string | null,
  } | null,
};

export type UpdateItineraryMutationVariables = {
  input: UpdateItineraryInput,
  condition?: ModelItineraryConditionInput | null,
};

export type UpdateItineraryMutation = {
  updateItinerary:  {
    __typename: "Itinerary",
    id: string,
    isRoot: boolean,
    name: string,
    description: string | null,
    start:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    end:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    code: Code | null,
    parentID: string,
    parent:  {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null,
    children:  {
      __typename: "ModelItineraryConnection",
      items:  Array< {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
    owner: string | null,
  } | null,
};

export type DeleteItineraryMutationVariables = {
  input: DeleteItineraryInput,
  condition?: ModelItineraryConditionInput | null,
};

export type DeleteItineraryMutation = {
  deleteItinerary:  {
    __typename: "Itinerary",
    id: string,
    isRoot: boolean,
    name: string,
    description: string | null,
    start:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    end:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    code: Code | null,
    parentID: string,
    parent:  {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null,
    children:  {
      __typename: "ModelItineraryConnection",
      items:  Array< {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
    owner: string | null,
  } | null,
};

export type SyncItinerariesQueryVariables = {
  filter?: ModelItineraryFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncItinerariesQuery = {
  syncItineraries:  {
    __typename: "ModelItineraryConnection",
    items:  Array< {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type GetItineraryQueryVariables = {
  id: string,
};

export type GetItineraryQuery = {
  getItinerary:  {
    __typename: "Itinerary",
    id: string,
    isRoot: boolean,
    name: string,
    description: string | null,
    start:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    end:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    code: Code | null,
    parentID: string,
    parent:  {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null,
    children:  {
      __typename: "ModelItineraryConnection",
      items:  Array< {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
    owner: string | null,
  } | null,
};

export type ListItinerarysQueryVariables = {
  filter?: ModelItineraryFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListItinerarysQuery = {
  listItinerarys:  {
    __typename: "ModelItineraryConnection",
    items:  Array< {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null > | null,
    nextToken: string | null,
    startedAt: number | null,
  } | null,
};

export type OnCreateItinerarySubscriptionVariables = {
  owner: string,
};

export type OnCreateItinerarySubscription = {
  onCreateItinerary:  {
    __typename: "Itinerary",
    id: string,
    isRoot: boolean,
    name: string,
    description: string | null,
    start:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    end:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    code: Code | null,
    parentID: string,
    parent:  {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null,
    children:  {
      __typename: "ModelItineraryConnection",
      items:  Array< {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
    owner: string | null,
  } | null,
};

export type OnUpdateItinerarySubscriptionVariables = {
  owner: string,
};

export type OnUpdateItinerarySubscription = {
  onUpdateItinerary:  {
    __typename: "Itinerary",
    id: string,
    isRoot: boolean,
    name: string,
    description: string | null,
    start:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    end:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    code: Code | null,
    parentID: string,
    parent:  {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null,
    children:  {
      __typename: "ModelItineraryConnection",
      items:  Array< {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
    owner: string | null,
  } | null,
};

export type OnDeleteItinerarySubscriptionVariables = {
  owner: string,
};

export type OnDeleteItinerarySubscription = {
  onDeleteItinerary:  {
    __typename: "Itinerary",
    id: string,
    isRoot: boolean,
    name: string,
    description: string | null,
    start:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    end:  {
      __typename: "TimeLocation",
      time: string,
      lat: number | null,
      long: number | null,
    },
    code: Code | null,
    parentID: string,
    parent:  {
      __typename: "Itinerary",
      id: string,
      isRoot: boolean,
      name: string,
      description: string | null,
      start:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      end:  {
        __typename: "TimeLocation",
        time: string,
        lat: number | null,
        long: number | null,
      },
      code: Code | null,
      parentID: string,
      parent:  {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null,
      children:  {
        __typename: "ModelItineraryConnection",
        nextToken: string | null,
        startedAt: number | null,
      } | null,
      _version: number,
      _deleted: boolean | null,
      _lastChangedAt: number,
      createdAt: string,
      updatedAt: string,
      owner: string | null,
    } | null,
    children:  {
      __typename: "ModelItineraryConnection",
      items:  Array< {
        __typename: "Itinerary",
        id: string,
        isRoot: boolean,
        name: string,
        description: string | null,
        code: Code | null,
        parentID: string,
        _version: number,
        _deleted: boolean | null,
        _lastChangedAt: number,
        createdAt: string,
        updatedAt: string,
        owner: string | null,
      } | null > | null,
      nextToken: string | null,
      startedAt: number | null,
    } | null,
    _version: number,
    _deleted: boolean | null,
    _lastChangedAt: number,
    createdAt: string,
    updatedAt: string,
    owner: string | null,
  } | null,
};
